---
# tasks file for libvirt-config

- name: add users to libvirtd group
  user:
    name: '{{ item }}'
    groups: libvirt
    append: yes
  with_items: "{{ libvirt_group_members }}"

- fail: 
    msg: "The system may not be provisioned according to the CMDB status."
  when: libvirt_rootserver_ifName not in hostvars[ansible_host]['ansible_interfaces']

- name: edit interfaces
  template:
    src: 'debian/network_interfaces.j2'
    dest: '/etc/network/interfaces'
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart networking

- name: Start networks if not started
  virt_net:
    name: 'default'
    state: 'active'
  become: False

#- name: Set autostart attribute on networks
#  virt_net:
#    name: 'default'
#    autostart: 'yes'
#  become: False
