---
# tasks file for libvirt-config

- name: add users to libvirtd group
  user:
    name: '{{ item }}'
    groups: libvirt
    append: yes
  with_items: "{{ libvirt_group_members }}"

- name: Fail if given interface not exist.
  fail:
    msg: "Given interface {{libvirt_rootserver_ifName}} not in systems interfaces list!"
  when: libvirt_rootserver_ifName not in hostvars[ansible_host]['ansible_interfaces']

- name: Fail if given public guest ip is not valid
  fail: 
    msg: "libvirt_rootserver_guestIP in wrong format: 'single', 'public' or '11.22.33.44/29'. Value: {{libvirt_rootserver_guestIP}}"
  when: libvirt_rootserver_guestIP != "False" and
        libvirt_rootserver_guestIP != "single" and
        not libvirt_rootserver_guestIP | ipaddr

- name: edit interfaces
  template:
    src: 'debian/network_interfaces.j2'
    dest: '/etc/network/interfaces'
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart networking

- name: Start networks if not started
  virt_net:
    name: 'default'
    state: 'active'
  become: False

#- name: Set autostart attribute on networks
#  virt_net:
#    name: 'default'
#    autostart: 'yes'
#  become: False
